def separate():
    print('=========================================')

def help():
    separate()
    print(f'Usage: school-organizer [command] [arguments]')
    separate()
    print(f'Commands:')
    print(f'help - Shows this help message')
    print(f'create - Creates a new class, subject, schedule, lesson, exam or homework')
    print(f'add - Adds a new lesson, exam or homework')
    print(f'list - Lists all classes, subjects, lessons, exams, homeworks or schedules')
    print(f'remove - Removes a class, subject, lesson, exam or homework')
    separate()
    print(f'Arguments:')
    print(f'create class [name] - Creates a new class')
    print(f'create subject [name] [class] - Creates a new subject')
    print(f'create schedule [class] [day] [start] [end] [subject] - Creates a new schedule')
    print(f'create lesson [class] [subject] [date] - Creates a new lesson')
    print(f'create exam [class] [subject] [date] [grade] - Creates a new exam')
    print(f'create homework [class] [subject] [date] [description] - Creates a new homework')
    print(f'add lesson [class] [subject] [date] - Adds a new lesson')
    print(f'add exam [class] [subject] [date] [grade] - Adds a new exam')
    print(f'add homework [class] [subject] [date] [description] - Adds a new homework')
    print(f'list classes - Lists all classes')
    print(f'list subjects [class] - Lists all subjects')
    print(f'list lessons [class] [subject] - Lists all lessons')
    print(f'list exams [class] - Lists all exams')
    print(f'list homeworks [class] - Lists all homeworks')
    print(f'list schedule [class] [day] [week] - Lists all schedules')
    print(f'remove class [name] - Removes a class')
    print(f'remove subject [name] [class] - Removes a subject')
    print(f'remove lesson [class] [subject] [date] - Removes a lesson')
    print(f'remove exam [class] [subject] [date] - Removes an exam')
    print(f'remove homework [class] [subject] [date] - Removes a homework')
    separate()
    print(f'Examples:')
    print(f'school-organizer create class 9A')
    print(f'school-organizer create subject Maths 9A')
    print(f'school-organizer create schedule 9A Monday 8:00 9:00 Maths')
    print(f'school-organizer create lesson 9A Maths 2021-01-01')
    print(f'school-organizer create exam 9A Maths 2021-01-01 10')
    print(f'school-organizer create homework 9A Maths 2021-01-01 "Do the homework"')
    print(f'school-organizer add lesson 9A Maths 2021-01-02')
    print(f'school-organizer add exam 9A Maths 2021-01-02 10')
    print(f'school-organizer add homework 9A Maths 2021-01-02 "Do the homework"')
    print(f'school-organizer list classes')
    print(f'school-organizer list subjects 9A')
    print(f'school-organizer list lessons 9A Maths')
    print(f'school-organizer list exams 9A')
    print(f'school-organizer list homeworks 9A')
    print(f'school-organizer list schedule 9A Monday')
    print(f'school-organizer remove class 9A')
    print(f'school-organizer remove subject Maths 9A')
    print(f'school-organizer remove lesson 9A Maths 2021-01-01')
    print(f'school-organizer remove exam 9A Maths 2021-01-01')
    print(f'school-organizer remove homework 9A Maths 2021-01-01')
    separate()

if __name__ == '__main__':
    help()
